export const FETCH_FEED_START = 'FETCH_FEED_START';
export const FETCH_FEED_SUCCESS = 'FETCH_FEED_SUCCESS';
export const FETCH_FEED_FAIL = 'FETCH_FEED_FAIL';

export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const GET_POST_START = 'GET_POST_START';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';

export const RETWEET_POST_SUCCESS = 'RETWEET_POST_SUCCESS';
export const RETWEET_POST_FAIL = 'RETWEET_POST_FAIL';

export const QUOTE_POST_SUCCESS = 'QUOTE_POST_SUCCESS';
export const QUOTE_POST_FAIL = 'QUOTE_POST_FAIL';

export const DELETE_RETWEET_SUCCESS = 'DELETE_RETWEET_SUCCESS';
export const DELETE_RETWEET_FAIL = 'DELETE_RETWEET_FAIL';

export const REPLY_POST_SUCCESS = 'REPLY_POST_SUCCESS';
export const REPLY_POST_FAIL = 'REPLY_POST_FAIL';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const PIN_POST_SUCCESS = 'PIN_POST_SUCCESS';
export const PIN_POST_FAIL = 'PIN_POST_FAIL';

export const BOOKMARK_POST_SUCCESS = 'BOOKMARK_POST_SUCCESS';
export const BOOKMARK_POST_FAIL = 'BOOKMARK_POST_FAIL';

export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL';

export const GET_USER_LINKS_START = 'GET_USER_LINKS_START';
export const GET_USER_LINKS_SUCCESS = 'GET_USER_LINKS_SUCCESS';
export const GET_USER_LINKS_FAIL = 'GET_USER_LINKS_FAIL';

export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL';

export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';
export const SEARCH_POSTS_FAIL = 'SEARCH_POSTS_FAIL';

export const GET_BOOKMARKED_POSTS_START = 'GET_BOOKMARKED_POSTS_START';
export const GET_BOOKMARKED_POSTS_SUCCESS = 'GET_BOOKMARKED_POSTS_SUCCESS';
export const GET_BOOKMARKED_POSTS_FAIL = 'GET_BOOKMARKED_POSTS_FAIL';
